### ISSUE TITLE
How to get to actually output this README update needed

### ISSUE THREAD

**Issue by richtong** [innovationOUtside/nb_js_diagrammers#4]
I did a pip install of nb_js_diagrammers and there are a few things that need to be changed in the README.

I'm happy to send you a PR, but they are:

There is a prerequisite that is not included as a dependency so to prepare for this you need to do in a single cell before anything else in the environment this is on jupyterlab 3.2.5 and Python 3.9.9

```
!pip install pyflowchart nb_js_diagrammers
%load_ext nb_js_diagrammers
```

You should probably note that in a cell you can't have the above, the cell has to start with the %% and then it works and the 
output returns is a document. Also the -o does not seem to work, for instance

```
%%flowchart_magic -h 100 -o flowchart.html
```

Dioes not create a .html

**Comment by psychemedia** [comment]
Hi

I just added a requirements files including `pyflowchart` (I'm not sure if there are other missing dependencies) and pushed a new version bundling it to PyPi.

Re: the `-o` switch: I'll try to take a look unless you have a fix?

**Comment by psychemedia** [comment]
Ah, re: the outfile, looks like I'd been experimenting with something and the `-o` isn't currently used in anything. I don't remember if the thing I'd been exploring was close to working or not (or perhaps a legacy from something else!)

**Comment by psychemedia** [comment]
I added a clarification to readme regarding block magics and the requirement that the `%%` is the first item in a cell.

**Comment by psychemedia** [comment]
Passing a filename via `-o` should now save the file to the specified HTML and *and* uses this file in the embedded iframe. *Not* specifying the outfile will cause the HTML to be loaded literally via an IFrame `srcdoc` attribute.
