### ISSUE TITLE
How to pass Python variables?

### ISSUE THREAD

**Issue by roger-yu-ds** [innovationOUtside/nb_js_diagrammers#7]
I'm using Python to create my `mermaid_string`, but how do I visualise this?

```
%%mermaid_magic

$mermaid_string
```
produces  `Syntax error in graph`
![image](https://user-images.githubusercontent.com/7835508/228430986-c2eb91cd-baf0-4f46-b0cb-11c37c79bba2.png)

**Comment by psychemedia** [comment]
At the moment I'm not sure you can do that?

One approach would be to create a line magic that would accept something like `--src mermaid_string`, check that `--src` exists, and then use the text associated with that variable.

**Comment by psychemedia** [comment]
@roger-yu-ds Just pushed an update to allow passing script via a variable in a couple of cases:

DEPRECATED - SEE LATER REPLY

The `flowchart_magic` and `mermaid_magic` also act as line magics. Put the diagram script into a variable (`my_script`) then call as `%mermaid_magic --src "$my_script" -h 1000` etc (the variable should be passed in quotes).

I tried to push to pypi but the action is just hanging (it says it's queued but maybe something is broken?) and I don't have time to investigate further right now.

**Comment by psychemedia** [comment]
Update to the above -  magic now uses local scope so just pass th name of the variable that contains your diagram description:

> The flowchart_magic and mermaid_magic also act as line magics. Put the diagram script into a variable (my_script) then call as %mermaid_magic --src my_script -h 1000 etc 

PyPi action also fixed (updated linux version in action)
